import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/provider/provider";
import { getServerSession } from "next-auth";
import NavBar from "./_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <Provider session={session}>
        <body
          className={inter.className + " flex flex-col min-h-screen w-full bg-black pt-20"}
        >
          <NavBar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
